# Generated by Django 3.2.13 on 2006-01-03 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobportals', '0003_auto_20060103_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportals.city'),
        ),
        migrations.AlterField(
            model_name='company',
            name='co_introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='co_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='co_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_of_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportals.state'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website_url',
            field=models.CharField(blank=True, help_text='for example https://example.com', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='educationalbackground',
            name='studying',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
