# Generated by Django 3.2.13 on 2006-01-03 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportals', '0004_auto_20060103_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalbackground',
            name='job',
        ),
    ]
