# Generated by Django 3.2.13 on 2006-01-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportals', '0006_alter_skill_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cooperation_type',
            field=models.CharField(blank=True, choices=[('full', 'full-time'), ('part', 'part-time'), ('remote', 'remote'), ('internship', 'internship')], default='full', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='degree_level',
            field=models.CharField(blank=True, choices=[('DI', 'Diploma'), ('BA', 'Bachelor'), ('MA', 'Master'), ('DO', 'Doctoral'), ('N', 'Does not matter')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='job',
            name='gender',
            field=models.CharField(blank=True, choices=[('N', 'Does not matter'), ('F', 'Female'), ('M', 'Male')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, choices=[('agreement', 'agreement'), ('3', 'from 3'), ('5', 'from 5'), ('8', 'from 8'), ('10', 'from 10'), ('12', 'from 12'), ('15', 'from 15')], default='agreement', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_experience',
            field=models.CharField(blank=True, choices=[('1-3', '1-3 years'), ('3-6', '3-6 years'), ('+6', '+6 years'), ('N', 'Does not matter')], max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='working_hoursand_days',
            field=models.CharField(blank=True, help_text='for example: 9 AM-5 PM all day of week', max_length=255),
        ),
    ]
